#!/bin/sh -e

# Make sure gmp is built with generic options.
cp gcc/gmp/configfsf.guess gcc/gmp/config.guess
cp gcc/gmp/configfsf.sub   gcc/gmp/config.sub

# Use lib not lib64 by default.
sed -i '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64
sed -i 's/lib64/lib/'       gcc/gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

export libat_cv_have_ifunc=no

../gcc/configure \
	--prefix=/usr \
	--libexecdir=/usr/lib \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--disable-multilib \
	--disable-symvers \
	--disable-libmpx \
	--disable-libmudflap \
	--disable-libsanitizer \
	--disable-werror \
	--disable-fixed-point \
	--disable-libstdcxx-pch \
	--disable-nls \
	--enable-tls \
	--enable-checking=release \
	--disable-sercureplt \
	--without-included-gettext \
	--enable-languages=c,c++ \
	--build=powerpc-linux-musl \
	--disable-libssp \
	--enable-deterministic-archives \
	--enable-libstdcxx-time \
	--enable-libstdcxx-time=rt \
	--enable-threads \
	--with-long-double-64 \
	--with-system-zlib

make
make DESTDIR="$1" install

# Save 35MB.
find "$1" -name libgtkpeer.a  -exec rm -f {} +
find "$1" -name libgjsmalsa.a -exec rm -f {} +
find "$1" -name libgij.a      -exec rm -f {} +

# Some legacy programs will expect cc
ln -s gcc "$1/usr/bin/cc"

# POSIX compliance.
install -Dm755 ../c99 "$1/usr/bin/c99"

# Symlink for LTO.
{
    mkdir -p "$1/usr/lib/bfd-plugins"

    ln -s "/usr/lib/gcc/x86_64-pc-linux-musl/$2/liblto_plugin.so" \
          "$1/usr/lib/bfd-plugins/liblto_plugin.so"
}
